# Generated by Django 5.0.2 on 2024-02-21 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comptoire', '0002_remove_etatsclient_etat'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayementClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('montant', models.FloatField()),
                ('propreot', models.IntegerField()),
                ('editeur', models.IntegerField()),
                ('type', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PayementEtablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('montant', models.FloatField()),
                ('propreot', models.IntegerField()),
                ('editeur', models.IntegerField()),
                ('type', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PayementFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('montant', models.FloatField()),
                ('propreot', models.IntegerField()),
                ('editeur', models.IntegerField()),
                ('type', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PayementSousTraitant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('montant', models.FloatField()),
                ('propreot', models.IntegerField()),
                ('editeur', models.IntegerField()),
                ('type', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RemiseClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('etablissement', models.IntegerField()),
                ('montant', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RemiseEtablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('etablissement', models.IntegerField()),
                ('montant', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RemiseFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('etablissement', models.IntegerField()),
                ('montant', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RemiseSousTraitent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('etablissement', models.IntegerField()),
                ('montant', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MvtStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte', models.FloatField()),
                ('entree', models.BooleanField()),
                ('sortie', models.BooleanField()),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comptoire.etablissement')),
                ('id_Art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comptoire.article')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte', models.FloatField()),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comptoire.etablissement')),
                ('id_Art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comptoire.article')),
            ],
        ),
    ]
