# Generated by Django 5.0.2 on 2024-03-07 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comptoire', '0003_payementclient_payementetablissement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonRecuperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('propretaire', models.IntegerField()),
                ('montant', models.FloatField()),
                ('editeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('etat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comptoire.etatoperations')),
                ('imprime', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comptoire.liseetatsortie')),
                ('type_payement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comptoire.typepayement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BonTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('propretaire', models.IntegerField()),
                ('montant', models.FloatField()),
                ('editeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('etat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comptoire.etatoperations')),
                ('imprime', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comptoire.liseetatsortie')),
                ('type_payement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comptoire.typepayement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BonTranzition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('propretaire', models.IntegerField()),
                ('montant', models.FloatField()),
                ('editeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('etat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comptoire.etatoperations')),
                ('imprime', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comptoire.liseetatsortie')),
                ('type_payement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comptoire.typepayement')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
